apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
  namespace: {{ .Values.jenkins.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      serviceAccountName: {{ .Values.jenkins.serviceAccountName }}
      containers:
        - name: jenkins
          image: {{ .Values.jenkins.image }}
          resources:
            {{- toYaml .Values.jenkins.resources | nindent 12 }}
          ports:
            - name: httpport
              containerPort: {{ .Values.jenkins.service.port }}
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: {{ .Values.jenkins.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: {{ .Values.jenkins.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
        {{- if .Values.dind.enabled }}
        - name: dind
          image: {{ .Values.dind.image }}
          securityContext:
            privileged: {{ .Values.dind.privileged }}
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
        {{- end }}
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        {{- if .Values.dind.enabled }}
        - name: docker-graph-storage
          emptyDir: {}
        {{- end }}
