# Jenkins configuration
jenkins:
  image: jenkins/jenkins:lts
  namespace: jenkins
  serviceAccountName: jenkins-admin
  resources:
    limits:
      memory: "4Gi"
      cpu: "2000m"
    requests:
      memory: "1Gi"
      cpu: "1000m"
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
    nodePort: 32000
  persistence:
    enabled: true
    storageClass: kar-storage
    size: 10Gi
    accessModes: ReadWriteOnce
    path: /mnt
    nodeAffinity:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - ip-10-0-46-115.ec2.internal

# Docker-in-Docker (DinD) configuration
dind:
  enabled: true
  image: docker:dind
  privileged: true

# RBAC configuration
rbac:
  enabled: true
  clusterRole:
    name: jenkins-admin-role
  clusterRoleBinding:
    name: jenkins-admin-RoleBinding

